
services:

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    restart: "unless-stopped"
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  workers:
    container_name: workers
    build:
      context: ./
      dockerfile: Dockerfile
    restart: "unless-stopped"
    env_file:
      - .env
    command: npm run start:workers
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
